---
title: "Bounded mean test - scribbles"
format: pdf
editor: source
---

## The problem

Given a sequence $X_1, X_2, \ldots$ of i.i.d. random variables with support on $[0, \infty)$ with the common distribution $X$ and CDF $F$. We want to:

a)  find a powerful test for the null $H_0 : E(X) \leq \mu$ against the alternative $H_1 : E(X) > \mu$ and/or
b)  compute a lower confidence bound on $E(X)$ with guaranteed coverage properties

While this is of interest by itself, we in the end want to combine two such one-sided tests to obtain a test/confidence interval for the mean of a variable over $[0,1]$ --- so if necessary, some extra assumptions can be made (e.g. all moments bounded).

Without loss of generality, we can scale the variables such that $\mu = 1$.

## Augmented bootstrap test

The overall idea: mixture of the bootstrap distribution with a proportion of zeroes, such that the mean is $1$

Note on notation: we will index all variables derived from the observed sample by the number of draws observed ($n$). Whenever we use $X$ without any index, we implicitly mean that the claim is true for all $X_i$.

Denote $\bar{X}_n = \frac{\sum_{i=1}^n X_i}{n}$.

For a sample of size $n$ we never reject when $\bar{X}_n \leq 1$. When $\bar{X}_n > 1$ we define r.v. $A_n = 1 - \frac{1}{\bar{X}_n}$.[^1] We construct $B_n$ as the mixture of a point mass at zero with weight $A_n$ and the bootstrap distribution with weight $1 - A_n$ and look at the distribution of the sample mean for those variables. More formally, we now consider the i.i.d random variables $Z_{n,1}, \ldots, Z_{n,n}$ with support $\{0, 1, \ldots, n\}$ and $B_{n,1}, \ldots, B_{n,n}$ over $[0, \infty)$. For all $i \in \{1, \ldots, n\}$ we have:

[^1]: Choosing $A$ in this way was suggested by an anonymous user on Cross Validated questions and answer site: https://stats.stackexchange.com/a/650747/73129

$$
\begin{aligned}
P(Z_{n,i} = 0) &= A_n = 1 - \frac{1}{\bar{X}_n}\\
P(Z_{n,i} = k) &= \frac{1 - A_n}{n} = \frac{1}{n \bar{X}_n} = \frac{1}{\sum_{i=1}^n X_i}  \text{ for } \ 0 < k \leq n \\
B_{n,i} &= \begin{cases} 0 & Z_{n,i} = 0 \\
X_{Z_{n,i}} & \text{otherwise} 
\end{cases}
\end{aligned}
$$

Note that $E(B_{n,i} | \bar{X}_n > 1) = 1$. Now we obtain the r.v. $S_n$

$$
S_n = \frac{1}{n}\sum_{i=1}^n B_{n,i}
$$

Note that given specific observations of $X_1, \ldots, X_n$ we can obtain samples of $S_n$ easily in a Monte Carlo fashion. We then reject at level $\alpha$ if the observed value of the mean is above the $1 - \alpha$ quantile of $S_n$. We now need to prove that this is a valid testing procedure.

So the $p$ value of observed datapoints $x_1, \ldots, x_n$ is:

$$
p_n(x_1, \ldots, x_n) = \begin{cases}
1 & \sum x_i \leq n \\
P(S_n \geq \frac{1}{n}\sum x_i | X_1 = x_1, ..., X_n = x_n) & \text{otherwise}
\end{cases}
$$

Which is valid if whenever $E(X) = 1$ then for all $0 < \alpha < 1$ we have:

$$
P(p(X_1, \ldots, X_n) < \alpha) < \alpha 
$$

i.e.

$$
P(E_B(\mathbb{I}(S_n \geq \bar{X}_n)) < \alpha \wedge \bar{X}_n > 1) < \alpha
$$

for $n = 1$:

$$
\begin{aligned}
P(E_B(\mathbb{I}(B_1 \geq X_1)) < \alpha \wedge X_1 > 1) &= \\
P(E_Z(Z_1 = 1) < \alpha \wedge X_1 > 1) &= \\
P(\frac{1}{X_1} < \alpha \wedge X_1 > 1) &= \\
P(X_1 > \frac{1}{\alpha} \wedge X_1 > 1) &= \\
P(X_1 > \frac{1}{\alpha}) & 
\end{aligned}
$$

Note that this means that this is proven to be the uniform most powerful non-randomized test for $n = 1$ in Wang & Zhao. 

Just to complete the proof: Since $E(X_1) = 1$ and $E(X_1) > \frac{1}{\alpha} P(X_1 > \frac{1}{\alpha})$ we have

$$
P(X_1 > \frac{1}{\alpha})  < \frac{1}{\frac{1}{\alpha}} = \alpha
$$

Now let's do $n=2$, assume. In this case, assuming $X_1 + X_2 > 2$ and $X_1 \neq X_2$ we get:

$$
E_B(\mathbb{I}(S_2 \geq \bar{X}_2)) = E_B(\mathbb{I}(B_{2,1} + B_{2,2} \geq X_1 + X_2)) = \frac{3}{(X_1 + X_2)^2}
$$
(we either need to pick $X_1$ and $X_2$ for $B$ or need to pick the larger value twice, each combination has prob $\frac{1}{(X_1 + X_2)^2}$)

i.e. we reject when

$$
\frac{3}{(X_1 + X_2)^2} < \alpha \\
X_1 + X_2 > \sqrt{\frac{3}{\alpha}}
$$

```{r}
x <- c(1,1.5)
ml_dap_p(x, mu = 1, alternative = "less", B = 1e7)
3/(sum(x)^2)
```


$$
X_1 = \sqrt{\frac{3}{\alpha}} - X_2
$$

If $Y_1, ..., Y_n$ are drawn from the same distr, we know that

$$
P_X(E_Y(\mathbb{I}(\frac{1}{n}\sum_1^n Y_i \geq \bar{X}_n)) < \alpha) < \alpha
$$

(that's just the correct sampling distribution)

If we could show:


$$ 
P_X(E_B(\mathbb{I}(S_n \geq \bar{X}\_n)) < \alpha \wedge \bar{X}\_n > 1) \leq P_X(E_Y(\mathbb{I}(\frac{1}{n}\sum\_1\^n Y_i \geq \bar{X}\_n)) < \alpha) \\

P_X(E_B(\mathbb{I}(\sum*{i=1}^n B*{n,i} \geq \sum*{i=1}\^n X_i)) \<* \alpha \wedge \sum{i=1}\^n X_i \> n1) \leq P_X(E_Y(\mathbb{I}(\sum*1\^n Y_i* \geq \sum{i=1}\^n X_i)) \< \alpha) \\
$$

Asymptotically as $n \to \infty$ we have $B_{n,i} \to Y_i$, so the inequality should hold in the limit.

It seems plausible that the behaviour between $1$ and $\infty$ should be "nice" and so the validity could follow from some sort of monotonicity/convexity argument, but I wasn't able to make it work so far.

$$
P_X(E_B(\mathbb{I}(\sum_{i=1}^n B_{n,i} \geq \sum_{i=1}^n X_i)) < \alpha \wedge \sum_{i=1}^n X_i > n)
$$

Expand the last var

$$
E_B\left(\mathbb{I}\left(\sum_{i=1}^n B_{n,i} \geq \sum_{i=1}^n X_i\right)\right)  =
A_n E_B\left(\mathbb{I}\left(\sum_{i=1}^{(n-1)} B_{n,i} \geq \sum_{i=1}^n X_i\right)\right)  + 
\frac{1}{\sum_{i=1}^n X_n} \sum_{b=1}^nE_B\left(\mathbb{I}\left(X_b +\sum_{i=1}^{(n-1)} B_{n,i} \geq \sum_{i=1}^n X_i \right)\right)
$$

$$
E_B\left(\mathbb{I}\left(\sum_{i=1}^n B_{n,i} \geq \sum_{i=1}^n X_i\right)\right)
$$

$$
X_1 = 1, X_2 = 2: \\
E_B\left(\mathbb{I}\left(B_{1,1} \geq X_1\right)\right) = 1-A_1 = \frac{\mu}{X_1} \\
E_B\left(\mathbb{I}\left(B_{2,1} + B_{2,2} \geq X_1 + X_2\right)\right) = 3\left(\frac{\mu}{3}\right)^2= \frac{\mu^2}{3}
$$

The test can then be inverted to obtain cofindence bounds.

## Approximate computation

Computation time gains (especially for larger $n$) likely possible with a saddlepoint approximation to the bootstrap distribution (https://www.jstor.org/stable/2336592). This will be particularly useful to compute extreme tail probabilities and to invert the test should we want to obtain confidence bounds.

## Possible extensions:

The current proposal assumes the CDF of the distribution is upper bounded by a CDF of a point mass at 0. The method should however work by replacing the point mass with an arbitrary distribution with known mean as long as its CDF bounds the set of distributions we want to test. Instead of adding $0$ to the bootstrap distribution we would then add draws from this bounding distribution.

## Literature

**Summary:** it appears that numerically the best performing method for variables bounded from both sides is that of Gaffke 2005, which is more thoroughly investigated in Learned-Miller and Thomas 2019 [A new confidence interval for the mean of a bounded random variable](https://arxiv.org/pdf/1905.06208). However, this method currently has been proven to be valid only in special cases. The proposed method gives numerically similar results to Gaffke, possible even slightly tighter.

**Individual works:**

A possibly oldest reference is Anderson 1969: [Confidence limits for the expected value of an arbitrary bounded random variable with a continuous distribution function](https://purl.stanford.edu/xc975jg9300) - Via Diouf and doufour better than Hoeffding and Hora & Hora

Bickel 1992: [Inference and Auditing: The Stringer Bound](https://doi.org/10.2307/1403650), discusses Stringer bound (strictly upper bound) and offers improvements. Uses a point mass at 1 in a special case, so related to my proposal, also uses the empirical distribution (of non-zero values). Claim one can move to two-sided bound. -\> Need to Romano & Wolf claim that methods are not conservative and efficient.

Diouf & Dufour 2005: [Improved Nonparametric Inference for the Mean of a Bounded Random Variable with Application to Poverty Measures](http://web.hec.ca/scse/articles/Diouf.pdf), improve the Anderson 1969 method and provide an additional set of intervals based on confidence bands for the CDF based on eCDF. There does not appear to be huge variability between the methods.

Learned-Miller and Thomas 2019 [A new confidence interval for the mean of a bounded random variable](https://arxiv.org/pdf/1905.06208) Mix the ordered observations with an ordered vector of uniformly distributed random variables. Compute with Monte Carlo (easy). Looks very good! Phan & Learned-Miller claim this to be rediscovery of Gaffke 2005. No proof of guaranteed coverage, only conjecture and proof for some special cases. TODO go through citing papers

Gaffke, N. Three test statistics for a nonparametric one- sided hypothesis on the mean of a nonnegative variable. Mathematical Methods of Statistics, 14(4):451–467, 2005. Matches the alg in Learned-Miller & Thomas, less evaluation.

Phan & Thomas & Learned-Miller 2021: [Towards Practical Mean Bounds for Small Samples](http://proceedings.mlr.press/v139/phan21a/phan21a.pdf) Claim that Diouf & Dufour as well as Romano & Wolf do not dominate Anderson, while their technique does. Do not compare to Gaffke/Learned-Miller & Thomas 2019 - presumably because it isn't better? But the method shares similarities - combine with a random uniform vector... Looks computationally mildly expensive (solve a linear program for each bootstrap sample).

Romano & Wolf 2000: [Finite sample nonparametric inference and large sample efficiency](https://doi.org/10.1214/aos/1015951997) prove that there is an asymptotic upper bound on efficiency of any test in this setting and construct an (IMHO somewhat clunky) test that meets this asymptotic bound.

Waudby-Smith & Aaditya Ramdas 2022: [Estimating means of bounded random variables by betting](https://arxiv.org/pdf/2010.09686) give both confidence intervals and confidence sequences, but focuse on the case of distributions over just $\{0,1\}$. Their bounds are valid for general distributions on $[0,1]$, but do not exploit the presence of intermediate values and are thus unnecessarily conservative. Discussion by Li, Li & Dai does some numerical comparisons. Supplementary Fig 16 has comparison to Phan & Thomas & Learned-Miller 2021 (favorable to Waudby-Smith). Basically admit Gafke/Learned-Miller and Thomas 2019 are much better.

Schlag's thesis [New Method for Constructing Exact Tests without Making any Assumptions](https://econ-papers.upf.edu/papers/1109.pdf) Numerical simulations lacking, but seems that with n = 60 still has about 1.5 times wider CI than asymptotic (Table 1). There's also a working paper Schlag 2013 [Exact Hypothesis Testing without Assumptions -New and Old Results not only for Experimental Game Theory](https://homepage.univie.ac.at/karl.schlag/research/statistics/exacthypothesistesting8.pdf) Repeatedly randomize to {0,1} and use a test on binary outcomes, then average. Just a test, no CI (But can be inverted). Implemented in the `npExact` R package.

Austern & Mackey 2024: [Efficient Concentration with Gaussian Approximation](https://arxiv.org/pdf/2208.09922). Close to asymptotic performance, but use pretty large n in experiments. Claim to outperform Romano & Wolf 202.

Orabona & Jun 2022, [Tight Concentrations and Confidence Sequences from the Regret of Universal Portfolio](https://arxiv.org/abs/2208.09922) A new concentration inequality, call it PRECiSE-A-CO96. Seems like minor improvement over Waudyb-Smith. Code in Matlab :-(. Require N \> 10000 to come close to asymptotic.

Fienberg, S. E., Neter, J., and Leitch, R. A. Estimating the total overstatement error in accounting populations. Journal of the American Statistical Association, 72(358): 295–302, 1977. Phan & Thomas & Learned-Miller 2021 claim this is nice but computationally intractable Estimates multinomial uncertainty for bins of (rounded) values and then combines those together to form confidence for the mean.

Wang, W., & Zhao, L. H. (2003). [Nonparametric tests for the mean of a non-negative population.](https://doi.org/10.1016/s0378-3758(01)00294-4). Looks just at an upper bound and constructs a uniformly most powerful test for $n \leq 2$. So maybe a good benchmark? (Theorem 5.2 and equation 5.3 seem to describe the test)

Shekhar & Ramdas 2023: [On the near-optimality of betting confidence sets for bounded means](https://arxiv.org/pdf/2310.01547). Another asymptotic bound on test efficiency, but with respect to a specific distribution. Claims Waudby-Smith & Ramdas 2023 is "near optimal" (weird, since we know it is weak) - compare just to an "Empirical Bernstein" bound. Looks at the asymptotic behaviour of $\limsup_{n\to \infty} \sqrt{n} w_n$ where $w_n$ is the width of the interval.

Maurer, A. and Pontil, M. Empirical Bernstein bounds and sample variance penalization. In Proceedings of the Twenty-Second Annual Conference on Learning Theory, pp. 115–124, 2009. Phan & Thomas & Learned-Miller 2021 claim this works poorly Paper has an inequality, but focuses on an application of the inequality. The inequality only uses mean and variance, hence likely weak.

Bentkus's concentration result - https://www.jstor.org/stable/3481693 (using only sum, so has to be weak, but better than Hoeffding) We won't discuss tests based on Hoeffding as it is shown to be substantially worse than many of the alternatives considered.

Bentkus & Zuijlen 2001: [Upper confidence bound for the mean](http://www.math.ru.nl/onderzoek/reports/rep2001/rep01_10.ps.gz) somewhat tightens other results, likely not so useful.

There are also more general frameworks looking at general moment inequalities e.g. [Romano, Shaikh & Wolf 2014](https://doi.org/10.3982/ECTA11011) or general functional inequalities e.g. [Lee, Song & Whang 2018](https://doi.org/10.1017/S0266466617000329), which we won't review further.

### Unprocessed refs I couldn't find

J. A. HORA and S. C. HORA. Nonparametric bounds for errors in dollar unit sampling based on the cumulative distribution function. Proceedings of the Decision Sciences Institute pp. 115—117 (1990). - Diouf & Dufour explain, claim far worse than asymptotic width (also symmetric around mean, which sounds bad).

V. K. SUTTON and D. M.YOUNG. A comparison of distribution-free confidence interval methods for estimating the mean of a random variable with bounded support. Baylor University, Department of Information Sys- tems (1997). -- Diouf & Dufour claim they find Fishman the best, Hora and Hora very wide.
