---
title: "Large model space selection with rjags"
format: html
editor: source
---

Ideas: change to uniform/Beta binomial to build dependence into the model indicators

```{r setup, message=FALSE,warning=FALSE, results="hide"}
library(SBC)
library(ggplot2)
library(dplyr)
library(tidyr)
library(calibrationband)

library(future)


cache_dir <- here::here("cache")
if(!dir.exists(cache_dir)) {
  dir.create(cache_dir)
}

compute_histories <- FALSE



theme_set(theme_minimal())
pkgload::load_all()
```


```{r cluster, results='hide', warning=FALSE, message=FALSE}
setup_cluster(max_server_workers = 100, max_local_workers = 10)
```


```{r}
one_sim_generator <- function(N, P, rho = 0, shape1 = 1, shape2 = 1) {
  beta <- rnorm(P, 0, 1)
  prob <- rbeta(1, shape1, shape2)
  m <- rbinom(P, size = 1, prob = prob)
  betaMod <- beta * m
  
  cor_m <- matrix(rho, nrow = P, ncol = P)
  diag(cor_m) <- 1
  X <- mvtnorm::rmvnorm(N,sigma = cor_m)
  X[,1] <- 1
  
  mu <- X %*% betaMod
  
  sd <- rexp(1)
  
  y <- rnorm(N, mu, sd)

  list(
    variables = list(beta = beta, m = m, m_bad = m, sd = sd, prob = prob),
    generated = list(X = X, n = N, p = P, y = y, shape1 = shape1, shape2 = shape2),
    var_attributes = var_attributes(m = c(binary_var_attribute(), possibly_constant_var_attribute()), m_bad = c(binary_var_attribute(), possibly_constant_var_attribute()))
  )
}

dq <- derived_quantities(
  log_lik = sum(dnorm(y, X %*% (beta * m),   sd, log = TRUE)),
  log_lik_bad = sum(dnorm(y, X %*% (beta * m_bad),   sd, log = TRUE)),
  model_index = as.numeric(paste0("0.", paste0(m, collapse = ""))),
  model_index_bad = as.numeric(paste0("0.", paste0(m_bad, collapse = ""))),
  graded_model_index = as.numeric(paste0(sum(m), ".", paste0(m, collapse = ""))),
  graded_model_index_bad = as.numeric(paste0(sum(m_bad), ".", paste0(m_bad, collapse = ""))),
  betaShift = dplyr::if_else(m == 1, beta, -10),
  betaShift_bad = dplyr::if_else(m_bad == 1, beta, -10),
  .var_attributes = var_attributes(model_index = possibly_constant_var_attribute(),model_index_bad = possibly_constant_var_attribute(), graded_model_index = possibly_constant_var_attribute(), 
                                   graded_model_index_bad = possibly_constant_var_attribute(), betaShift = possibly_constant_var_attribute(), betaShift_bad = possibly_constant_var_attribute())
)

rho <- 0.8
shape1 <- 1
shape2 <- 1
param_cache_text <- paste0(if_else(rho == 0, "", paste0("_rho_", rho)), "_sh_", shape1, "_", shape2)
```

```{r}
backend_rjags_wrapped <- function(..., n_shuffle = 0) {
  res <- SBC_backend_rjags(...)
  class(res) <- c("backend_rjags_wrapped", class(res))
  res$n_shuffle <- n_shuffle
  res
}

SBC_fit.backend_rjags_wrapped <- function(backend, ...) {
  res <- NextMethod()
  class(res) <- c("backend_rjags_wrapped_fit", class(res))
  res$n_shuffle <- backend$n_shuffle
  res
}


SBC_fit_to_draws_matrix.backend_rjags_wrapped_fit <- function(fit) {
  res <- NextMethod()
  n_shuffle <- fit$n_shuffle
  
  m_draws <- posterior::as_draws_array(res)[, , grepl("^m\\[[0-9]*\\]$", posterior::variables(res))]

  indices_to_shuffle <- sample.int(dim(m_draws)[3], size = n_shuffle)
  perm_to_shuffle <- sample(indices_to_shuffle, size = n_shuffle)
    
  bad_draws <- m_draws
  bad_draws[,,indices_to_shuffle] <- m_draws[,,perm_to_shuffle]
  
  bad_draws <- posterior::as_draws_matrix(bad_draws)
  posterior::variables(bad_draws) <- sub("m", "m_bad", posterior::variables(bad_draws))
  posterior::bind_draws(res, bad_draws)
}


SBC_fit_specific_dquants.backend_rjags_wrapped_fit <- function(fit) {
  # Working with string representation of the models as I may need over 100bits of information so ints/doubles are not enough
  samples_matrix <- SBC_fit_to_draws_matrix(fit)
  model_samples_matrix <- samples_matrix[, grepl("^m\\[[0-9]*\\]$", colnames(samples_matrix))]
  full_model_samples <- apply(model_samples_matrix, MARGIN = 1, FUN = paste0, collapse = "")
  full_model_table <- table(full_model_samples)

  max_entry_id <- which.max(full_model_table)
  max_model_string <- names(full_model_table)[max_entry_id]
  max_model_vector <- stringr::str_split_1(max_model_string, pattern = "")

  dq_string <- paste0("m[", 1:length(max_model_vector), "] == ", max_model_vector, collapse = " && ")
  
  ## Duplicate for _bad, a bit inelegant, sorry
  model_samples_matrix_bad <- samples_matrix[, grepl("^m_bad\\[[0-9]*\\]$", colnames(samples_matrix))]
  full_model_samples_bad <- apply(model_samples_matrix_bad, MARGIN = 1, FUN = paste0, collapse = "")
  full_model_table_bad <- table(full_model_samples_bad)

  max_entry_id_bad <- which.max(full_model_table_bad)
  max_model_string_bad <- names(full_model_table_bad)[max_entry_id_bad]
  max_model_vector_bad <- stringr::str_split_1(max_model_string_bad, pattern = "")

  dq_string_bad <- paste0("m_bad[", 1:length(max_model_vector_bad), "] == ", max_model_vector_bad, collapse = " && ")
  
  do.call(derived_quantities, list(top_model = rlang::parse_quo(dq_string, rlang::current_env()),
                                   top_model_bad = rlang::parse_quo(dq_string_bad, rlang::current_env()),
                     .var_attributes = var_attributes(top_model = c(possibly_constant_var_attribute(), binary_var_attribute()),
                     top_model_bad = c(possibly_constant_var_attribute(), binary_var_attribute()))))
}

my_globals <- c("SBC_fit_specific_dquants.backend_rjags_wrapped_fit", "SBC_fit.backend_rjags_wrapped", "SBC_fit_to_draws_matrix.backend_rjags_wrapped_fit")
```


## Small

```{r}
backend_small <- backend_rjags_wrapped("linear-selection.jags", n.iter = 20000, n.burnin = 5000, n.chains = 4, thin = 10, variable.names = c("beta", "m", "sd", "prob"), n_shuffle = 2)

```


```{r small-datasets}
set.seed(655223142)
ds_small <- generate_datasets(SBC_generator_function(one_sim_generator, N = 50, P = 4, rho = rho, shape1 = shape1, shape2 = shape2, future.chunk.size = Inf), n_sims = 10000)
```


```{r small}

res_small <- compute_SBC(ds_small, backend_small, 
                         keep_fits = length(ds_small) <= 100,
                         dquants = dq,
                         globals = my_globals,
                         cache_mode = "results",
                         cache_location = file.path(cache_dir, paste0("SBC_linear_rjags_small_N", length(ds_small), param_cache_text, ".rds")))
```

```{r small-metrics}
small_stats_ok <- res_small$stats |> filter(!grepl("_bad", variable))
small_stats_bad <- res_small$stats |> filter(grepl("_bad", variable))

bp_small <- binary_probabilities_from_stats_empirical(res_small$stats)


metrics_small <- SBCBayesFactors:::calibration_metrics_per_variable(bp_small, prob1_prior_spec = list("top_model_bad" = "avg_true"))
metrics_small_ok <- metrics_small[!grepl("_bad", names(metrics_small))]
metrics_small_bad <- metrics_small[grepl("_bad", names(metrics_small))]

```


The normal stats are OK

```{r}
plot_ecdf_diff(small_stats_ok, combine_variables = combine_array_elements)

purrr::iwalk(metrics_small_ok, \(metrics, name) {cat("\n=====", name, "====\n"); print(metrics)})
```


The bad (shuffled) stats are bad

```{r}
plot_ecdf_diff(small_stats_bad, combine_variables = combine_array_elements)

purrr::iwalk(metrics_small_bad, \(metrics, name) {cat("\n=====", name, "====\n"); print(metrics)})
```

### Histories

```{r}
n_histories <- 100
main_vars <- c("model_index_bad","graded_model_index_bad", "top_model_bad", "log_lik_bad")
```



```{r small-histories}
hist_length_small <- 500
invisible(get_precomputed_gamma_thresholds(unique(res_small$stats$max_rank) + 1,min_sims = 1, max_sims = max(1000, hist_length_small)))

hist_step_small <- 10
hist_small <- compute_bootstrapped_histories(res_small$stats |> filter(variable %in% main_vars | grepl("m_bad", variable)), history_length = hist_length_small, n_histories = n_histories, step = hist_step_small,
                                            compute_log_gamma_history)

bp_small_bad <- bp_small |> filter(grepl("_bad", variable))

hist_small_ttest_m <- compute_bootstrapped_histories(bp_small_bad |> filter(variable != "top_model_bad"), history_length = hist_length_small, n_histories = n_histories, step = hist_step_small,
                                            compute_ttest_history, expected = 0.5, min_sim_id = 5)

hist_small_ttest_m_aggregated <- aggregate_log_p_histories(hist_small_ttest_m, new_var = "m_aggregated")

hist_small_ttest_top <- compute_bootstrapped_histories(bp_small_bad  |> filter(variable == "top_model_bad"), history_length = hist_length_small, n_histories = n_histories, step = hist_step_small,
                                            compute_ttest_history, expected = "avg_true", min_sim_id = 5)

hist_small_ttest <- rbind(hist_small_ttest_m, hist_small_ttest_m_aggregated, hist_small_ttest_top)



# hist_small_ttest_short <- compute_bootstrapped_histories(bp_small_bad |> filter(variable == "is_model0"), history_length = 2000, n_histories = n_histories, step = 5,
#                                             compute_ttest_history, expected = 0.25)


hist_small_brier <- compute_bootstrapped_histories(bp_small_bad, history_length = hist_length_small, n_histories = n_histories, step = hist_step_small,
                                            compute_brier_history, min_sim_id = 10)

hist_small_brier_aggregated <- aggregate_log_p_histories(hist_small_brier |> filter(grepl("m_bad", variable)), new_var = "m_aggregated")


hist_small_miscalibration <- compute_bootstrapped_histories(bp_small_bad, history_length = hist_length_small, n_histories = n_histories, step = hist_step_small,
                                                           compute_miscalibration_history, min_sim_id = 10)

hist_small_miscalibration_aggregated <- aggregate_log_p_histories(hist_small_miscalibration |> filter(grepl("m_bad", variable)), new_var = "m_aggregated")



plot_log_gamma_histories(hist_small)
plot_log_p_histories(rbind(hist_small_brier, hist_small_brier_aggregated), "Brier resampling")
plot_log_p_histories(hist_small_ttest, "P - ttest")

plot_log_p_histories(rbind(hist_small_miscalibration, hist_small_miscalibration_aggregated), "Miscalibration resampling")

# save_histories("large_linear_rjags_small",
#                log_gamma = hist_small,
#                brier = hist_small_brier_aggregated,
#                ttest = hist_small_ttest,
#                #ttest_short = hist_small_ttest_short,
#                miscalibration = hist_small_miscalibration_agregated)

```



## Large

```{r large-datasets}
set.seed(2465223)
ds_large <- generate_datasets(SBC_generator_function(one_sim_generator, N = 80, P = 100, rho = rho, shape1 = shape1, shape2 = shape2, future.chunk.size = Inf), n_sims = 1000)
```


```{r}
backend_large <- backend_rjags_wrapped("linear-selection.jags", n.iter = 400000, n.burnin = 50000, n.chains = 4, thin = 100, variable.names = c("beta", "m", "sd", "prob"),
                                           n_shuffle = 20)
```


```{r large-all}
res_large <- compute_SBC_cache_blocks(ds_large, backend_large, 
                         keep_fits = FALSE,
                         globals = my_globals,
                         dquants = dq,
                         cache_prefix = file.path(cache_dir, paste0("SBC_linear_rjags_large", param_cache_text,"_")),
                         block_size = 100)

```

```{r}
res_large <- get_partial_cache_blocks(ds_large, backend_large,
                         keep_fits = FALSE,
                         globals = my_globals,
                         dquants = dq,
                         cache_prefix = file.path(cache_dir, paste0("SBC_linear_rjags_large", param_cache_text,"_")),
                         block_size = 100)

```


```{r large-metrics}
large_stats_ok <- res_large$stats |> filter(!grepl("_bad", variable))
large_stats_bad <- res_large$stats |> filter(grepl("_bad", variable))

bp_large <- binary_probabilities_from_stats_empirical(res_large$stats)

metrics_large <- SBCBayesFactors:::calibration_metrics_per_variable(bp_large |> filter(grepl("^m", variable)), include_reliability_diag = FALSE, B = 20000)
metrics_large_ok <- metrics_large[!grepl("_bad", names(metrics_large))]
metrics_large_bad <- metrics_large[grepl("_bad", names(metrics_large))]

metrics_large_df <- purrr::imap_dfr(metrics_large, calibration_metrics_to_df) |> mutate(bad = grepl("_bad", variable))

metrics_large_df_ss <- metrics_large_df |> 
  summarise(
  min_DAP_p = min(DAP_p),
  DAP_rejection = mean(DAP_p < 0.05),
  min_miscalibration_p = min(miscalibration_p),
  miscalibration_rejection = mean(miscalibration_p < 0.05),
  min_log_gamma_m_threshold = min(log_gamma - log_gamma_limit),
  log_gamma_rejection = mean(log_gamma < log_gamma_limit),
  .by = bad
)

```


The normal stats are OK

```{r}
plot_ecdf_diff(large_stats_ok, combine_variables = combine_array_elements)

calibration_metrics(bp_large |> filter(variable == "top_model"), prob1_prior = "avg_true" )

metrics_large_df_ss |> filter(!bad) |> select(-bad)
```


The bad (shuffled) stats are bad

```{r}
plot_ecdf_diff(large_stats_bad, combine_variables = combine_array_elements)

calibration_metrics(bp_large |> filter(variable == "top_model_bad"), prob1_prior = "avg_true" )

metrics_large_df_ss |> filter(bad) |> select(-bad)
```


```{r}
bp_large |> filter(grepl("m_bad\\[[0-9]\\]", variable)) |> plot_binary_calibration()
min(p.adjust(metrics_large_df |> filter(bad) |> pull(miscalibration_p), method = "holm"))
min(p.adjust(metrics_large_df |> filter(bad) |> pull(DAP_p), method = "holm"))
```



### Histories

```{r}
n_histories <- 100
main_vars <- c("model_index_bad","graded_model_index_bad", "top_model_bad", "log_lik_bad")
```



```{r large-histories}
hist_length_large <- 500
invisible(get_precomputed_gamma_thresholds(unique(res_large$stats$max_rank) + 1,min_sims = 1, max_sims = max(1000, hist_length_large)))

hist_step_large <- 50
hist_large <- compute_bootstrapped_histories(res_large$stats |> filter(variable %in% main_vars | grepl("m_bad", variable)), history_length = hist_length_large, n_histories = n_histories, step = hist_step_large,
                                            compute_log_gamma_history)

bp_large_bad <- bp_large |> filter(grepl("_bad", variable))

hist_large_ttest_m <- compute_bootstrapped_histories(bp_large_bad |> filter(variable != "top_model_bad"), history_length = hist_length_large, n_histories = n_histories, step = hist_step_large,
                                            compute_ttest_history, expected = 0.5, min_sim_id = 5)

hist_large_ttest_m_aggregated <- aggregate_log_p_histories(hist_large_ttest_m, new_var = "m_aggregated")

hist_large_ttest_top <- compute_bootstrapped_histories(bp_large_bad  |> filter(variable == "top_model_bad"), history_length = hist_length_large, n_histories = n_histories, step = hist_step_large,
                                            compute_ttest_history, expected = "avg_true", min_sim_id = 5)

hist_large_ttest <- rbind(hist_large_ttest_m_aggregated, hist_large_ttest_top, hist_large_ttest_m |> filter(grepl("m_bad.[1-6].$", variable)))



hist_large_brier_all <- compute_bootstrapped_histories(bp_large_bad, history_length = hist_length_large, n_histories = n_histories, step = hist_step_large,
                                            compute_brier_history, min_sim_id = 10, B = 20000)

hist_large_brier_aggregated <- aggregate_log_p_histories(hist_large_brier_all |> filter(grepl("m_bad", variable)), new_var = "m_aggregated")

hist_large_brier <- rbind(
  hist_large_brier_all |> filter(variable == "top_model_bad" | grepl("m_bad.[1-6].$", variable)),
  hist_large_brier_aggregated
)

hist_large_miscalibration_all <- compute_bootstrapped_histories(bp_large_bad, history_length = hist_length_large, n_histories = n_histories, step = hist_step_large,
                                                           compute_miscalibration_history, min_sim_id = 10, B = 20000)

hist_large_miscalibration_aggregated <- aggregate_log_p_histories(hist_large_miscalibration_all |> filter(grepl("m_bad", variable)), new_var = "m_aggregated")

hist_large_miscalibration <- rbind(
  hist_large_miscalibration_all |> filter(variable == "top_model_bad" | grepl("m_bad.[1-6].$", variable)),
  hist_large_miscalibration_aggregated
)


plot_log_gamma_histories(hist_large |> filter(!grepl("m_bad", variable) | grepl("m_bad.[1-6].$", variable)))
plot_log_p_histories(hist_large_brier, "Brier resampling")
plot_log_p_histories(hist_large_miscalibration, "Miscalibration resampling")
plot_log_p_histories(hist_large_ttest, "P - ttest")


save_histories("large_linear_rjags_large",
               log_gamma = hist_large,
               brier = hist_large_brier,
               ttest = hist_large_ttest,
               miscalibration = hist_large_miscalibration)

```

