---
title: "Linear regression - multiple models"
format: html
---

TODO: SBC progressr signal errors, dependency on MCMCpack,
BF diags - always start with HX:

Let's setup the environment (bridgesampling currently works only with rstan):

```{r setup, message=FALSE,warning=FALSE, results="hide"}
library(SBC)
library(ggplot2)
library(bridgesampling)
library(brms)
library(dplyr)
library(tidyr)
library(calibrationband)

use_cmdstanr <- FALSE
library(rstan)
rstan_options(auto_write = TRUE)

library(future)


cache_dir <- here::here("cache")
if(!dir.exists(cache_dir)) {
  dir.create(cache_dir)
}



options(SBC.min_chunk_size = 10)


theme_set(theme_minimal())
pkgload::load_all()
```

```{r}
# Global settings for the scenario
do_tests <- FALSE
add_x0 <- FALSE
N <- 60
G <- 15
n_sims <- 1000
```


```{r cluster}
setup_cluster(max_server_workers = 60, max_local_workers = 10)
```




## Simulator

```{r}
prior_args <- list(
  b_sd = 0.25,
  intercept_mean = 2,
  intercept_sd = 2,
  sigma_sd = 3,
  tau_shape = 8,
  tau_rate = 4
)

one_sim_generator <- function(N, G, model, prior_args, add_x0 = FALSE) {
  if(add_x0) {
    x0 <- rnorm(N)
  }
  x1 <- rnorm(N)
  x2 <- rnorm(N)
  
  group = rep(1:G, length.out = N)
  
  b_Intercept <- rnorm(1, prior_args$intercept_mean, prior_args$intercept_sd)   
  sigma <- abs(rnorm(1, 0, prior_args$sigma_sd))

  tau <- rgamma(1, shape = prior_args$tau_shape, rate = prior_args$tau_rate)
  
  lprior <- dnorm(b_Intercept, prior_args$intercept_mean, prior_args$intercept_sd, log = TRUE) +
    log(2) + dnorm(sigma, 0, prior_args$sigma_sd, log = TRUE) +
    dgamma(tau, shape = prior_args$tau_shape, rate = prior_args$tau_rate, log = TRUE)

  if(add_x0) {
    b_x0 <- rnorm(1, 0, prior_args$b_sd)
    lprior <- lprior + dnorm(b_x0,  0, sd = prior_args$b_sd, log = TRUE)
  }

  if( (model %% 2) == 1) {
    b_x1 <- rnorm(1, 0, prior_args$b_sd)
    lprior <- lprior + dnorm(b_x1, 0, sd = prior_args$b_sd, log = TRUE)
  } else {
    b_x1 <- 0
  }
  
  if(model > 1) {
    b_x2 <- rnorm(1, 0, prior_args$b_sd)
    lprior <- lprior + dnorm(b_x2, 0, sd = prior_args$b_sd, log = TRUE)
  } else {
    b_x2 <- 0
  }
  
  ranef_raw <- rnorm(G)
  ranef <- ranef_raw * tau
  
  predictor <- b_Intercept + x1 * b_x1 + x2 * b_x2 + ranef[group]
  if(add_x0) {
    predictor <- predictor + x0 * b_x0
  }
  y <- rnorm(N, predictor, sigma)
  
  lranef <- sum(dnorm(ranef_raw, log = TRUE))
  
  ljacobian <- log(sigma) + log(tau)
  lobs <- sum(dnorm(y, predictor, sigma, log = TRUE))
  lp__ <- lprior + ljacobian + lobs + lranef
    
  variables <- list(
      b_Intercept = b_Intercept,
      sigma = sigma,
      lprior = lprior,
      sd_group__Intercept = tau,
      z_1 = matrix(ranef_raw, nrow = 1, ncol = G),
      lp__ = lp__
    )
  
  if(add_x0) {
    variables$b_x0 <- b_x0
  }
  
  if( (model %% 2) == 1) {
    variables$b_x1 <- b_x1
  }
  
  if(model > 1) {
    variables$b_x2 <- b_x2
  }

  
  generated <- data.frame(y = y, x1 = x1, x2 = x2, group = group)
  if(add_x0) {
    generated$x0 <- x0
  }
  list(
    variables = variables,
    generated = generated
  )
}
```

```{r}
gen_H0 <- SBC_generator_function(one_sim_generator, N = N, G = G, model = 0, prior_args = prior_args, add_x0 = add_x0)
gen_H1 <- SBC_generator_function(one_sim_generator, N = N, G = G, model = 1, prior_args = prior_args, add_x0 = add_x0)
gen_H2 <- SBC_generator_function(one_sim_generator, N = N, G = G, model = 2, prior_args = prior_args, add_x0 = add_x0)
gen_H3 <- SBC_generator_function(one_sim_generator, N = N, G = G, model = 3, prior_args = prior_args, add_x0 = add_x0)

```


```{r backends}
prior <- c(set_prior(paste0("normal(0,", prior_args$b_sd,")"), class = "b"),
           set_prior(paste0("normal(0,", prior_args$sigma_sd,")"), class = "sigma"),
           set_prior(paste0("normal(", prior_args$intercept_mean,", ", prior_args$intercept_sd,")"), class = "b", coef = "Intercept"),
           #set_prior(paste0("normal(0,", prior_args$tau_sd,")"), class = "sd")
           set_prior(paste0("gamma(", prior_args$tau_shape, ",", prior_args$tau_rate,")"), class = "sd")
           )

template_data <- one_sim_generator(N, 3, 3, prior_args)$generated

chains <- 2
iter <- 21000
warmup <- 1000
thin_ranks <- floor((iter - warmup) / 400)
# chains <- 4
# iter <- 2000
# warmup <- 1000
# thin_ranks <- 10

control <- list(adapt_delta = 0.9, max_treedepth = 11)

H0_formula <- y ~ 0 + Intercept + (1 | group)
if(add_x0) {
  H0_formula <- update.formula(H0_formula, . ~ . + x0)
  H0_prior <- prior
} else {
  H0_prior <- prior[2:nrow(prior),]
}

backend_H0 <- SBC_backend_brms(
  H0_formula,
  prior = H0_prior,
  chains = chains,
  iter = iter,
  warmup = warmup,
  sample_prior = "yes",
  control = control,
  template_data = template_data,
  out_stan_file = file.path(cache_dir, paste0("lmm_multiple", if_else(add_x0, "_x0", ""),"_0.stan"))
)

backend_H1 <- 
  SBC_backend_brms(
    update.formula(H0_formula, . ~ . + x1),
    prior = prior,
    chains = chains,
    iter = iter,
    warmup = warmup,
    sample_prior = "yes",
    control = control,
    template_data = template_data,
    out_stan_file = file.path(cache_dir, paste0("lmm_multiple", if_else(add_x0, "_x0", ""),"_1.stan"))
  )

backend_H2 <- SBC_backend_brms(
    update.formula(H0_formula, . ~ . + x2),
  prior = prior,
  chains = chains,
  iter = iter,
  warmup = warmup,
  sample_prior = "yes",
  control = control,
  template_data = template_data,
  out_stan_file = file.path(cache_dir, paste0("lmm_multiple", if_else(add_x0, "_x0", ""),"_2.stan"))
)

backend_H3 <-
    SBC_backend_brms(
    update.formula(H0_formula, . ~ . + x1 + x2),
      prior = prior,
      chains = chains,
      iter = iter,
      warmup = warmup,
      sample_prior = "yes",
      control = control,
      template_data = template_data,
      out_stan_file = file.path(cache_dir, paste0("lmm_multiple", if_else(add_x0, "_x0", ""),"_3.stan"))
    )
  
    

```


## Test individual models

```{r test0}
if(do_tests) {
  n_sims_for_test <- 1000 
  all_generators <- list("H0" = gen_H0, "H1" = gen_H1, "H2" = gen_H2, "H3" = gen_H3)
  all_backends <- list("H0" = backend_H0, "H1" = backend_H1, "H2" = backend_H2, "H3" = backend_H3)
  
  for(m_name in names(all_generators)) {
    cat("=========== Testing ", m_name, "===============\n")
    set.seed(321485652)
    ds_test <- generate_datasets(n_sims = n_sims_for_test, all_generators[[m_name]])
    res_test <- compute_SBC(ds_test, all_backends[[m_name]], 
                           keep_fits = FALSE,
                           cache_mode = "results",
                           thin_ranks = thin_ranks,
                           cache_location = file.path(cache_dir, paste0("SBC_lmm_",m_name,"_N", N, "_G", G, "_", length(ds_test), ".rds")))
  
    print(res_test)
    print(plot_ecdf_diff(res_test, combine_variables = SBC::combine_array_elements) + ggtitle(m_name))    
  }

}
```



```{r}
# id <- which.min(res_test$default_diagnostics$min_ess_to_rank)
# fit <- SBC_fit(all_backends[[m_name]], ds_test$generated[[id]])
# #posterior::variables(fit)
# #"^b|^sd|sigma|z_1\\[1,1\\]"
# posterior::summarise_draws(posterior::as_draws(fit))
# draws <- posterior::subset_draws(posterior::as_draws(fit), variable ="^b|^sd|^sigma|z_1\\[1,1\\]", regex = TRUE)
# bayesplot::mcmc_pairs(draws, np = nuts_params(fit))
# 
# res_test$stats |> filter(sim_id == id)
# 
# bayesplot::mcmc_scatter(draws, pars = c("sd_group__Intercept", "sigma"), np = nuts_params(fit), size = 1, alpha = 0.1, transformations = "log")
```



## Savage-Dickey + bridgesampling - combined


### Definitions

Via `hypothesis`


```{r}
dm_thin <- 25

stopifnot(thin_ranks / dm_thin == floor(thin_ranks / dm_thin))

# Set H1_backend to NULL to do the stupid square trick
SBC_backend_savage_dickey <- function(backend_H0, backend_H1, backend_H2, backend_H3, savd_draws = 2000, few_draws = 15) {
  structure(list(backend_H0 = backend_H0, backend_H1 = backend_H1, backend_H2 = backend_H2, backend_H3 = backend_H3, savd_draws = savd_draws, few_draws = few_draws), class = "SBC_backend_savage_dickey")
}

SBC_fit.SBC_backend_savage_dickey <- function(backend, generated, cores) {
  backend_bs <- SBC_backend_bridgesampling(backend$backend_H0,
                                           backend$backend_H1,
                                           backend$backend_H2,
                                           backend$backend_H3)
  fit <- list(savd_draws = backend$savd_draws, 
              few_draws = backend$few_draws,
              fit_bs = SBC_fit(backend_bs, generated, cores))
  structure(fit, class = "SBC_fit_savage_dickey")
}

#prefixes <- c("bs", "OK", "stupid", "OKfew", "stupidfew", "noiseprob", "noiseER", "noiseERtop")
prefixes <- c("bs", "OK", "stupid", "OKfew", "noiseprob", "noiseER", "noiseERtop")

fit_savage_dickey_to_probs <- function(fit) {
  probs <- list()
  
  probs$bs <- SBC:::SBC_fit_bridgesampling_to_probs(fit$fit_bs)

  if(!is.null(fit$savd_draws)) {
    fit_H0 <- shredder::stan_slice(fit$fit_bs$fits[[1]], 1:fit$savd_draws)
    fit_H1 <- shredder::stan_slice(fit$fit_bs$fits[[2]], 1:fit$savd_draws)
    fit_H2 <- shredder::stan_slice(fit$fit_bs$fits[[3]], 1:fit$savd_draws)
    fit_H3 <- shredder::stan_slice(fit$fit_bs$fits[[4]], 1:fit$savd_draws)
  } else {
    fit_H0 <- fit$fit_bs$fits[[1]]
    fit_H1 <- fit$fit_bs$fits[[2]]
    fit_H2 <- fit$fit_bs$fits[[3]]
    fit_H3 <- fit$fit_bs$fits[[4]]
  }
  
  probs_correct <- function(fit_H1, fit_H3) {
    h_H3 <- brms::hypothesis(fit_H3, c("x2 = 0", "x1 = 0"))
    h_H1 <- brms::hypothesis(fit_H1, "x1 = 0")
    evid_ratios <- c(h_H1$hypothesis$Evid.Ratio * h_H3$hypothesis$Evid.Ratio[1], h_H3$hypothesis$Evid.Ratio, 1)
    evid_ratios / sum(evid_ratios)
  }
  
  probs_stupid <- function(fit_H3) {
    h_H3 <- brms::hypothesis(fit_H3, c("x1^2 + x2^2 = 0", "x2 = 0", "x1 = 0"))
    evid_ratios <- c(h_H3$hypothesis$Evid.Ratio, 1)
    evid_ratios / sum(evid_ratios)
  }
  
  # Correct probs
  probs$OK <- probs_correct(fit_H1, fit_H3)
  
  # Stupid trick
  probs$stupid <-probs_stupid(fit_H3)
  
  H1_shred_few <- shredder::stan_slice(fit_H1, 1:fit$few_draws)
  H3_shred_few <- shredder::stan_slice(fit_H3, 1:fit$few_draws)

  probs$OKfew <- probs_correct(H1_shred_few, H3_shred_few)

  probs$noiseprob <- as.numeric(MCMCpack::rdirichlet(1, 9 * probs$OK))

  evidRatiosNoise2 <- exp(log(probs$OK / probs$OK[4]) + rnorm(4, sd = 0.5)) 
  probs$noiseER <- evidRatiosNoise2 / sum(evidRatiosNoise2)

  evidRatiosNoise3 <- probs$OK / probs$OK[4]
  evidRatiosNoise3[which.max(probs$OK)] <- exp(log(evidRatiosNoise3[which.max(probs$OK)]) + abs(rnorm(1)))     
  probs$noiseERtop <- evidRatiosNoise3 / sum(evidRatiosNoise3)
      
  probs
}

SBC_fit_to_draws_matrix.SBC_fit_savage_dickey <- function(fit) {
  probs <- fit_savage_dickey_to_probs(fit)

  draws_list <- purrr::map(fit$fit_bs$fits, function(x) {          
       posterior::thin_draws(posterior::merge_chains(SBC_fit_to_draws_matrix(x)), thin = dm_thin)
    })
  ndraws <- posterior::ndraws(draws_list[[1]])
  
  combined_draws_list <- list()
  for(name_prefix in names(probs)) {
    model_draws <- sample(0:3, size  = ndraws, prob = probs[[name_prefix]], replace = TRUE)
    combined_draws <- SBC:::combine_draws_matrix_for_bf(draws_list, model_draws, model_var = "model")
    posterior::variables(combined_draws) <- paste0(name_prefix, "_", posterior::variables(combined_draws))
    combined_draws_list[[name_prefix]] <- combined_draws
  }

  do.call(posterior::bind_draws, unname(combined_draws_list))
}

SBC_posterior_cdf.SBC_fit_savage_dickey <- function(fit, variables) {
  probs <- fit_savage_dickey_to_probs(fit)
  cdf_list <- list()
  for(name_prefix in names(probs)) {
    prefix_regex <- paste0("^", name_prefix, "_")
    variables_without_prefix <- variables[grepl(prefix_regex, names(variables))]
    names(variables_without_prefix) <- gsub(prefix_regex, "", names(variables_without_prefix))
    cdf <- SBC::posterior_cdf_from_model_probs(probs[[name_prefix]], "model", variables_without_prefix)
    cdf <- dplyr::mutate(cdf, variable = paste0(name_prefix, "_", variable))
    
    
    cdf_list[[name_prefix]] <- cdf
  }
  
  do.call(rbind, unname(cdf_list))
}


SBC_fit_specific_dquants.SBC_fit_savage_dickey <- function(fit) {
  probs <- fit_savage_dickey_to_probs(fit)
  dq_args <- list()
  for(prefix in prefixes) {
     max_index <- which.max(probs[[prefix]])
     is_var_name <- paste0(prefix, "_is_model", max_index - 1)
     top_var_name <- paste0(prefix, "_top_model")
     dq_args[[top_var_name]] <- rlang::parse_quo(is_var_name, rlang::current_env())
  }
 dq_args$.var_attributes <- SBC:::var_attributes_from_list(paste0(prefixes, "_top_model"), 
           list(c(binary_var_attribute(), possibly_constant_var_attribute())))
 do.call(derived_quantities, dq_args)
}

SBC_backend_hash_for_cache.SBC_backend_savage_dickey <- function(backend) {
  backend_for_hash <- backend
  for(hname in paste0("H", 0:3)) {
    backend_for_hash[[hname]] <- SBC_backend_hash_for_cache(backend_for_hash[[hname]])
  }
  rlang::hash(backend_for_hash)
}

SBC_fit_to_diagnostics.SBC_fit_savage_dickey <- function(fit, fit_output, fit_messages, fit_warnings) {
  SBC_fit_to_diagnostics(fit$fit_bs, fit_output, fit_messages, fit_warnings)
}

globals_savd <- c("prefixes",
                  "dm_thin",
                  "SBC_fit.SBC_backend_savage_dickey",
                  "fit_savage_dickey_to_probs",
                  "SBC_fit_to_draws_matrix.SBC_fit_savage_dickey",
                  "SBC_posterior_cdf.SBC_fit_savage_dickey",
                  "SBC_fit_specific_dquants.SBC_fit_savage_dickey",
                  "SBC_backend_hash_for_cache.SBC_backend_savage_dickey",
                  "SBC_fit_to_diagnostics.SBC_fit_savage_dickey")
```

### Datasets

```{r}
generator_combined_savd <- function(n_sims, combine_seed = NULL) {
  datasets_H0 <- generate_datasets(n_sims = n_sims, gen_H0)
  datasets_H1 <- generate_datasets(n_sims = n_sims, gen_H1)
  datasets_H2 <- generate_datasets(n_sims = n_sims, gen_H2)
  datasets_H3 <- generate_datasets(n_sims = n_sims, gen_H3)
  
  if(!is.null(combine_seed)) {
    set.seed(combine_seed)  
  }
  datasets_combined <- SBC_datasets_for_bf(datasets_H0, datasets_H1, datasets_H2, datasets_H3)
  
  draws_add_prefix <- function(draws, prefix) {
    posterior::variables(draws) <- paste0(prefix, "_", posterior::variables(draws))
    draws
  }
  
  var_attributes_add_prefix <- function(var_attributes, prefix) {
    names(var_attributes) <- paste0(prefix, "_", names(var_attributes))
    var_attributes
  }
  
  variables_prefixed <- do.call(posterior::bind_draws,
                                purrr::map(prefixes, function(prefix)
                                  draws_add_prefix(datasets_combined$variables, prefix)))
  
  var_attributes_prefixed <- do.call(
    combine_var_attributes,
    purrr::map(prefixes, function(prefix)
      var_attributes_add_prefix(datasets_combined$var_attributes, prefix))
  )
  
  datasets_combined_savd <- SBC_datasets(variables_prefixed,
                                         datasets_combined$generated,
                                         var_attributes_prefixed)
  datasets_combined_savd
} 
```


```{r}
set.seed(21485642)
datasets_combined_savd1 <- generator_combined_savd(n_sims, combine_seed = 6321485)
```


```{r}
#plan(sequential)
# results_test <- compute_SBC(datasets_combined_savd1[1:2], SBC_backend_savage_dickey(backend_H0, backend_H1, backend_H2, backend_H3),
#                           keep_fits = TRUE,
#                           globals = globals_savd
#                           )
# results_test
# results_test$stats
# results_test$errors
# 
# binary_probabilities_from_stats(results_test$stat)
# 
# vars <- as.numeric(datasets_combined_savd$variables[1,])
# names(vars) = posterior::variables(datasets_combined_savd$variables)
# fit <- results_test$fits[[1]]
# variables <- vars
# SBC_posterior_cdf(results_test$fits[[1]], vars)
```

### Computation

```{r}
results_savd1 <- compute_SBC(datasets_combined_savd1, SBC_backend_savage_dickey(backend_H0, backend_H1, backend_H2, backend_H3), 
                          keep_fits = FALSE,
                          cache_mode = "results",
                          cache_location = file.path(cache_dir, paste0("SBC_lmm_savage_dickey_N", N, "_G", G, "_", length(datasets_combined_savd1), ".rds")),
                          thin_ranks = thin_ranks / dm_thin,
                          globals = globals_savd
                          )
results_savd1



```

```{r}
set.seed(86548266)
n_sims2 <- 2000
datasets_combined_savd2 <- generator_combined_savd(n_sims2)

```

```{r}
results_savd2 <- compute_SBC(datasets_combined_savd2, SBC_backend_savage_dickey(backend_H0, backend_H1, backend_H2, backend_H3), 
                          keep_fits = FALSE,
                          cache_mode = "results",
                          cache_location = file.path(cache_dir, paste0("SBC_lmm_savage_dickey2_N", N, "_G", G, "_", length(datasets_combined_savd2), ".rds")),
                          thin_ranks = thin_ranks / dm_thin,
                          globals = globals_savd
                          )
results_savd2

```


```{r}
results_savd <- bind_results(results_savd1, results_savd2)

stats_by_prefix <- list()
for(prefix in prefixes) {
  prefix_regex <- paste0("^", prefix,"_")
  stats_by_prefix[[prefix]] <- results_savd$stats |> filter(grepl(prefix_regex, variable)) |> 
    mutate(variable = gsub(prefix_regex, "", variable))
}
```


```{r}
purrr::iwalk(stats_by_prefix, \(stats_sub, prefix) {
  print(plot_ecdf_diff(stats_sub, combine_variables = SBC::combine_array_elements) + ggtitle(prefix))
})
```


```{r calib-multiple-savd}
purrr::iwalk(stats_by_prefix, \(stats_sub, prefix) {
  print(plot_binary_calibration(binary_probabilities_from_stats(stats_sub), region.method = "resampling") + ggtitle(prefix))
})
```

```{r}
bp_bs <- binary_probabilities_from_stats(stats_by_prefix$bs)
purrr::iwalk(stats_by_prefix, \(stats_sub, prefix) {
  if(prefix == "bs") {
    return()
  }
  
  bp_savd <- binary_probabilities_from_stats(stats_sub)

  bp_savd_notop <- bp_savd |> filter(variable != "top_model")
  bp_bs_notop <- bp_bs |> filter(variable != "top_model", sim_id %in% bp_savd$sim_id)


stopifnot(identical(bp_savd_notop$sim_id, bp_bs_notop$sim_id))
stopifnot(identical(bp_savd_notop$variable, bp_bs_notop$variable))
stopifnot(identical(bp_savd_notop$simulated_value, bp_bs_notop$simulated_value))

bp_comparison <- bp_bs_notop |> 
  select(sim_id, variable, simulated_value, prob) |> 
  rename(prob_bs = prob) |> 
  mutate(prob_savd = bp_savd_notop$prob)

print(
bp_comparison |> ggplot() + aes(x = prob_bs, y = prob_savd) + geom_abline(color = "orangered", intercept = 0, slope = 1) +
  geom_point(alpha = 0.3) + facet_wrap(~variable) + coord_fixed() + 
  ggtitle(prefix)
)
print(bp_comparison |> group_by(sim_id) |> 
  mutate(EvidR_bs = pmax(1e-15, prob_bs / prob_bs[variable == "is_model3"]),
         EvidR_savd = pmax(1e-15, prob_savd / prob_savd[variable == "is_model3"])) |> 
  ungroup() |> 
  filter(variable != "is_model3") |> 
  ggplot() + aes(x = EvidR_bs, y = EvidR_savd) + geom_abline(color = "orangered", intercept = 0, slope = 1) +
  geom_point(alpha = 0.3) + facet_wrap(~variable) + coord_fixed() + scale_x_log10() + scale_y_log10() + ggtitle(prefix))
})
```




```{r}
test_results <- furrr::future_imap_dfr(stats_by_prefix, \(stats_sub, prefix) {
  bp <- binary_probabilities_from_stats(stats_sub)
  purrr::map_dfr(c("top_model", paste0("is_model", 0:3)), \(var) {
    bp_selected <- bp |> filter(variable == var)
    miscalib_test <- miscalibration_resampling_test(bp_selected$prob, bp_selected$simulated_value)
    brier_test <- brier_resampling_test(bp_selected$prob, bp_selected$simulated_value)
    if(var == "top_model") {
      dap_test <- t.test(bp_selected$prob, bp_selected$simulated_value)
    } else {
      dap_test <- t.test(bp_selected$prob, mu = 0.25)
    }
    data.frame(
      prefix = prefix,
      variable = var,
      miscalib = miscalib_test$p.value,
      brier = brier_test$p.value,
      dap = dap_test$p.value
    ) 
  })
}, .options = furrr::furrr_options(seed = TRUE))

test_results |> pivot_longer(c("miscalib", "brier", "dap"), names_to = "test", values_to = "p") |>  
  mutate(p = pmax(5e-05, p)) |>  # Avoid p-values lower than the lowest possible for the resampling tests
  ggplot() + aes(x = test, y = p, group = variable, color = variable)  + geom_hline(yintercept = 0.05, color = "orangered", linewidth = 1) + geom_point() + geom_line()+ scale_y_log10() + facet_wrap(~prefix, scales = "free_y")

```

```{r}
test_results
```


### Histories

```{r}
n_histories <- 100
hist_length_noiseER <- 800
invisible(get_precomputed_gamma_thresholds(unique(stats_by_prefix$noiseER$max_rank) + 1,min_sims = 1, max_sims = hist_length_noiseER))

hist_step_noiseER <- 100
hist_noiseER <- compute_bootstrapped_histories(stats_by_prefix$noiseER, history_length = hist_length_noiseER, n_histories = n_histories, step = hist_step_noiseER,
                                             compute_log_gamma_history)

bp_noiseER <- binary_probabilities_from_stats(stats_by_prefix$noiseER)

hist_noiseER_ttest_notop <- compute_bootstrapped_histories(bp_noiseER |> filter(variable != "top_model"), history_length = hist_length_noiseER, n_histories = n_histories, step = hist_step_noiseER,
                                            compute_ttest_history, expected = 0.25)

hist_noiseER_ttest_top <- compute_bootstrapped_histories(bp_noiseER  |> filter(variable == "top_model"), history_length = hist_length_noiseER, n_histories = n_histories, step = hist_step_noiseER,
                                            compute_ttest_history, expected = "avg_true")

hist_noiseER_ttest <- rbind(hist_noiseER_ttest_notop, hist_noiseER_ttest_top)

hist_noiseER_brier <- compute_bootstrapped_histories(bp_noiseER, history_length = hist_length_noiseER, n_histories = n_histories, step = hist_step_noiseER,
                                            compute_brier_history, min_sim_id = 10)


hist_noiseER_miscalibration <- compute_bootstrapped_histories(bp_noiseER, history_length = hist_length_noiseER, n_histories = n_histories, step = hist_step_noiseER,
                                                           compute_miscalibration_history, min_sim_id = 10)



main_vars <- c("model", paste0("is_model", 0:3), "top_model", "lp__", "lprior", "b_x1", "b_x2")
plot_log_gamma_histories(hist_noiseER |> filter(variable %in% main_vars))
plot_log_p_histories(hist_noiseER_brier, "Brier resampling")
plot_log_p_histories(hist_noiseER_ttest, "P - ttest")
plot_log_p_histories(hist_noiseER_miscalibration, "Miscalibration resampling")

save_histories("lmm_multiple_noiseER",
               log_gamma = hist_noiseER,
               brier = hist_noiseER_brier,
               ttest = hist_noiseER_ttest,
               miscalibration = hist_noiseER_miscalibration)
```


```{r}
n_histories <- 100
hist_length_stupid <- 1000
invisible(get_precomputed_gamma_thresholds(unique(stats_by_prefix$stupid$max_rank) + 1,min_sims = 1, max_sims = hist_length_stupid))

hist_step_stupid <- 20
hist_stupid <- compute_bootstrapped_histories(stats_by_prefix$stupid, history_length = hist_length_stupid, n_histories = n_histories, step = hist_step_stupid,
                                            compute_log_gamma_history)

bp_stupid <- binary_probabilities_from_stats(stats_by_prefix$stupid)

hist_stupid_ttest_notop <- compute_bootstrapped_histories(bp_stupid |> filter(variable != "top_model"), history_length = hist_length_stupid, n_histories = n_histories, step = hist_step_stupid,
                                            compute_ttest_history, expected = 0.25)

hist_stupid_ttest_top <- compute_bootstrapped_histories(bp_stupid  |> filter(variable == "top_model"), history_length = hist_length_stupid, n_histories = n_histories, step = hist_step_stupid,
                                            compute_ttest_history, expected = "avg_true")

hist_stupid_ttest <- rbind(hist_stupid_ttest_notop, hist_stupid_ttest_top)



hist_stupid_brier <- compute_bootstrapped_histories(bp_stupid, history_length = hist_length_stupid, n_histories = n_histories, step = hist_step_stupid,
                                            compute_brier_history, min_sim_id = 10)


hist_stupid_miscalibration <- compute_bootstrapped_histories(bp_stupid, history_length = hist_length_stupid, n_histories = n_histories, step = hist_step_stupid,
                                                           compute_miscalibration_history, min_sim_id = 10)




plot_log_gamma_histories(hist_stupid |> filter(variable %in% main_vars))
plot_log_p_histories(hist_stupid_brier, "Brier resampling")
plot_log_p_histories(hist_stupid_ttest, "P - ttest")
plot_log_p_histories(hist_stupid_miscalibration, "Miscalibration resampling")

save_histories("lmm_multiple_stupid",
               log_gamma = hist_stupid,
               brier = hist_stupid_brier,
               ttest = hist_stupid_ttest,
               miscalibration = hist_stupid_miscalibration)
```

```{r}
n_histories <- 100
hist_length_OKfew <- 1000
invisible(get_precomputed_gamma_thresholds(unique(stats_by_prefix$OKfew$max_rank) + 1,min_sims = 1, max_sims = hist_length_OKfew))

hist_step_OKfew <- 20
hist_OKfew <- compute_bootstrapped_histories(stats_by_prefix$OKfew, history_length = hist_length_OKfew, n_histories = n_histories, step = hist_step_OKfew,
                                            compute_log_gamma_history)

bp_OKfew <- binary_probabilities_from_stats(stats_by_prefix$OKfew)

hist_OKfew_ttest_notop <- compute_bootstrapped_histories(bp_OKfew |> filter(variable != "top_model"), history_length = hist_length_OKfew, n_histories = n_histories, step = hist_step_OKfew,
                                            compute_ttest_history, expected = 0.25)

hist_OKfew_ttest_top <- compute_bootstrapped_histories(bp_OKfew  |> filter(variable == "top_model"), history_length = hist_length_OKfew, n_histories = n_histories, step = hist_step_OKfew,
                                            compute_ttest_history, expected = "avg_true")

hist_OKfew_ttest <- rbind(hist_OKfew_ttest_notop, hist_OKfew_ttest_top)



hist_OKfew_brier <- compute_bootstrapped_histories(bp_OKfew, history_length = hist_length_OKfew, n_histories = n_histories, step = hist_step_OKfew,
                                            compute_brier_history, min_sim_id = 10)


hist_OKfew_miscalibration <- compute_bootstrapped_histories(bp_OKfew, history_length = hist_length_OKfew, n_histories = n_histories, step = hist_step_OKfew,
                                                           compute_miscalibration_history, min_sim_id = 10)




plot_log_gamma_histories(hist_OKfew |> filter(variable %in% main_vars))
plot_log_p_histories(hist_OKfew_brier, "Brier resampling")
plot_log_p_histories(hist_OKfew_ttest, "P - ttest")
plot_log_p_histories(hist_OKfew_miscalibration, "Miscalibration resampling")

save_histories("lmm_multiple_OKfew",
               log_gamma = hist_OKfew,
               brier = hist_OKfew_brier,
               ttest = hist_OKfew_ttest,
               miscalibration = hist_OKfew_miscalibration)
```


```{r}
n_histories <- 100
hist_length_noiseERtop <- 500
invisible(get_precomputed_gamma_thresholds(unique(stats_by_prefix$noiseERtop$max_rank) + 1,min_sims = 1, max_sims = hist_length_noiseERtop))

hist_step_noiseERtop <- 5
hist_noiseERtop <- compute_bootstrapped_histories(stats_by_prefix$noiseERtop, history_length = hist_length_noiseERtop, n_histories = n_histories, step = hist_step_noiseERtop,
                                             compute_log_gamma_history)

bp_noiseERtop <- binary_probabilities_from_stats(stats_by_prefix$noiseERtop)

hist_noiseERtop_ttest_notop <- compute_bootstrapped_histories(bp_noiseERtop |> filter(variable != "top_model"), history_length = hist_length_noiseERtop, n_histories = n_histories, step = hist_step_noiseERtop,
                                            compute_ttest_history, expected = 0.25)

hist_noiseERtop_ttest_top <- compute_bootstrapped_histories(bp_noiseERtop  |> filter(variable == "top_model"), history_length = hist_length_noiseERtop, n_histories = n_histories, step = hist_step_noiseERtop,
                                            compute_ttest_history, expected = "avg_true")



hist_noiseERtop_brier <- compute_bootstrapped_histories(bp_noiseERtop, history_length = hist_length_noiseERtop, n_histories = n_histories, step = hist_step_noiseERtop,
                                            compute_brier_history, min_sim_id = 10)


hist_noiseERtop_miscalibration <- compute_bootstrapped_histories(bp_noiseERtop, history_length = hist_length_noiseERtop, n_histories = n_histories, step = hist_step_noiseERtop,
                                                           compute_miscalibration_history, min_sim_id = 10)




plot_log_gamma_histories(hist_noiseERtop |> filter(variable %in% main_vars))
plot_log_p_histories(hist_noiseERtop_brier, "Brier resampling")
plot_log_p_histories(hist_noiseERtop_ttest, "P - ttest")
plot_log_p_histories(hist_noiseERtop_miscalibration, "Miscalibration resampling")

save_histories("lmm_multiple_noiseERtop",
               log_gamma = hist_noiseERtop,
               brier = hist_noiseERtop_brier,
               ttest = hist_noiseERtop_ttest,
               miscalibration = hist_noiseERtop_miscalibration)
```
